### ISSUE TITLE
[Ideas] Fallbacks for css properties

### ISSUE THREAD

**Issue by d4rkr00t** [brickss-css/brickss#29]
In css it's quite common to have something like that:

```css
.className {
  background: red;
  background: linear-gradient(#e66465, #9198e5);
}
```

E.g. if browser doesn't support `linear-gradient` it will fallback to previous value.

One of the options to support that in JavaScript object syntax which doesn't allow us to have duplicate properties (it does but there might be complications with typescript and parsers, e.g. babel !needs verification!), could be:

```js
let styles = css({
  background: ['red', 'linear-gradient(#e66465, #9198e5)']
});
```
